Repository DataDog/datadog-trace-agent, pull requests merged in 2018-06, with the labels that each got.

#430 cmd/trace-agent: improvements to trace/transaction writing pipeline.
  cmd/trace-agent/agent.go
  cmd/trace-agent/transaction_sampler.go
  cmd/trace-agent/transaction_sampler_test.go
  info/writer.go
  writer/trace_writer.go
  writer/trace_writer_test.go
Labels: core

#429 cmd/trace-agent: add a metric when the agent starts.
  cmd/trace-agent/main.go
Labels: core

#435 cmd/trace-agent: default to YAML config
  Makefile
  README.md
  cmd/trace-agent/agent.go
  cmd/trace-agent/agent_test.go
  cmd/trace-agent/main.go
  cmd/trace-agent/main_nix.go
  cmd/trace-agent/main_windows.go
  cmd/trace-agent/receiver.go
  cmd/trace-agent/receiver_test.go
  config/agent.go
  config/agent_nix.go
  config/agent_test.go
  config/agent_windows.go
  config/ini_file.go
  config/merge_env.go
  config/merge_ini.go
  config/merge_yaml.go
  filters/resource_test.go
  flags/flags.go
  flags/flags_nix.go
  flags/flags_windows.go
  info/info.go
  info/info_test.go
  info/test_cases/okay.json
  info/test_cases/warning.json
  osutil/file.go
  writer/stats_writer.go
  writer/stats_writer_test.go
  writer/trace_writer.go
  writer/trace_writer_test.go
Labels: core, enhancement

#439 model: improve normalization error logging
  model/normalizer.go
Labels: enhancement

#437 quantizer: allow variable assignments in SQL queries
  quantizer/sql.go
  quantizer/sql_test.go
  quantizer/tokenizer.go
Labels: bug

#444 Makefile: add new packages to linter
  Makefile
  flags/flags.go
  flags/flags_nix.go
Labels: dev/tooling

#446 LICENSE: add 3rd party LICENSE
  LICENSE-3rdparty.csv
Labels: docs
