Repository DataDog/datadog-trace-agent, pull requests merged in 2018-11, with the labels that each got.

#518 cmd/trace-agent: cover for log level "warning"
  cmd/trace-agent/main.go
Labels: enhancement

#519 config: enable to set "MaxTPS" from environment variable
  config/merge_env.go
  config/merge_env_test.go
Labels: enhancement

#529 writer: fix flaky test and add INTEGRATION env. flag for long tests
  Makefile
  cmd/trace-agent/agent_test.go
  writer/stats_writer_test.go
Labels: bug

#512 {config,flags}: change Windows paths from hard-coded to detecting program files
  config/config_windows.go
  flags/flags_windows.go
Labels: bug, enhancement
