Repository DataDog/datadog-trace-agent, pull requests merged in 2018-12, with the labels that each got.

#544 test: add integration package
  .gitignore
  Makefile
  cmd/trace-agent/agent_test.go
  cmd/trace-agent/model_test.go
  internal/api/api_test.go
  internal/config/apply.go
  internal/event/sampler_max_eps_test.go
  internal/filters/blacklister_test.go
  internal/test/agent.go
  internal/test/backend.go
  internal/test/buffer.go
  internal/test/buffer_test.go
  internal/test/doc.go
  internal/test/example_test.go
  internal/test/runner.go
  internal/test/testsuite/hostname_test.go
  internal/test/testutil/backoff.go
  internal/test/testutil/random.go
  internal/test/testutil/sampler.go
  internal/test/testutil/services.go
  internal/test/testutil/span.go
  internal/test/testutil/span_test.go
  internal/test/testutil/stats.go
  internal/test/testutil/stats_test.go
  internal/test/testutil/statsd.go
  internal/test/testutil/testutil.go
  internal/test/testutil/trace.go
  internal/writer/fixtures_test.go
  internal/writer/multi_test.go
  internal/writer/payload_test.go
  internal/writer/service_test.go
  internal/writer/stats_test.go
  internal/writer/trace_test.go
Labels: dev/testing, dev/tooling

#549 Update dependency on datadog-agent
  Gopkg.lock
  vendor/github.com/DataDog/datadog-agent/pkg/api/security/security.go
  vendor/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/kube_services.go
  vendor/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/kube_services_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/providers.go
  vendor/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/utils.go
  vendor/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/utils_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/collector/corechecks/checkbase.go
  vendor/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker.go
  vendor/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/config/config.go
  vendor/github.com/DataDog/datadog-agent/pkg/config/config_template.yaml
  vendor/github.com/DataDog/datadog-agent/pkg/config/config_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/config/legacy/converter.go
  vendor/github.com/DataDog/datadog-agent/pkg/config/legacy/converter_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/secrets/check_right.go
  vendor/github.com/DataDog/datadog-agent/pkg/secrets/secrets.go
  vendor/github.com/DataDog/datadog-agent/pkg/secrets/secrets_win.go
  vendor/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go
  vendor/github.com/DataDog/datadog-agent/pkg/tagger/collectors/kubernetes_main.go
  vendor/github.com/DataDog/datadog-agent/pkg/tagger/tagger.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/cgroup_metrics.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/disk.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/disk_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/network.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/network_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/containers/metrics/types.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/ecs/ecs.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/hostname.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/kubernetes/apiserver/controllers.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/kubernetes/apiserver/endpoints.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/kubernetes/apiserver/endpoints_test.go
  vendor/github.com/DataDog/datadog-agent/pkg/util/log/log_test.go
Labels: core

#551 Makefile: update cross-compilation script
  Makefile
  README.md
Labels: dev/tooling
